logging:
  level:
    root: info
    "[com.example.demo.**]": debug
    
spring:
  h2:
    console:
      enabled: false
  autoconfigure:
    exclude:
    # 使用druid-spring-boot-starter，但是在springboot的启动类上exclude掉DruidDataSourceAutoConfigure这个类，忽略druid连接池的默认数据源配置
    # 参考：https://www.cnblogs.com/ybyn/p/13690752.html
    - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  shardingsphere:
    mode:
      type: Standalone
    props:
      sql-show: true
    datasource:
        names: ds0
        ds0:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/test
          username: test
          password: test
    rules:
      sharding:
        tables:
          t_orders:
            logicTable: t_orders
            actual-data-nodes: ds0.t_orders_$->{0..1}
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: order_inline
            key-generator:
              column: order_id
              type: SNOWFLAKE
          t_fixed_date:
            logicTable: t_fixed_date
            actual-data-nodes: ds0.t_fixed_date_${2022}${(1..4).collect{t -> t.toString().padLeft(2, '0')}}
            table-strategy:
              standard:
                sharding-column: create_time
                sharding-algorithm-name: time_inline
            key-generator:
              column: id
              type: SNOWFLAKE
            key-generate-strategy:
              column:  id
              key-generator-name: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE
        sharding-algorithms:
          order_inline:
            type: inline
            props:
              algorithm-expression: t_orders_$->{order_id % 2}
          time_inline:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.demo.sharding.AppStandardShardingAlgorithm
                
              
